### ISSUE TITLE
Chrome Extension

### ISSUE THREAD

**Issue by emersonlaurentino** [rodrilima/corona-analytic-api#2]
Criei uma Extensão para o Chrome que consome sua API.

https://github.com/emersonlaurentino/covid-19braziltracker

**Comment by rodrilima** [comment]
Ficou show de bola !!

**Comment by emersonlaurentino** [comment]
Estou apenas aguardando a publicação na Chrome Web Store

**Comment by vitorhugosg** [comment]
Ficou dahora, parabéns!

**Comment by rodrilima** [comment]
Adicionei no Showcase do nosso README ! Parabéns mais uma vez pelo projeto.
