### ISSUE TITLE
merge date and time in an field that uses unix timestamp or other safer alternative

### ISSUE THREAD

**Issue by vitordino** [rodrilima/corona-analytic-api#7]
[dates and time are confusing](https://gist.github.com/timvisee/fcda9bbdff88d45cc9061606b4b923ca), let the user of the api decide how to tackle with it 😉

**Comment by raphaelkieling** [comment]
What is your ideia? The source of the data is the `http://plataforma.saude.gov.br/novocoronavirus/resources/scripts/database.js` it's use a simple `DD/MM/YYYY`. We don't have more information :disappointed:

**Comment by raphaelkieling** [comment]
I did this but i need that my last pr would be aproved to create new pr

**Comment by raphaelkieling** [comment]
I did use a ISO8601 is more usualy tha the unix inside a api response, what you think about that :timer_clock:

**Comment by rodrilima** [comment]
Done. Thanks @raphaelkieling !
